// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartStock.Server.Data;

#nullable disable

namespace SmartStock.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826063144_AddProducts")]
    partial class AddProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartStock.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "...",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "...",
                            Name = "Laptops",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "...",
                            Name = "Desktops",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "...",
                            Name = "Smartphones",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "...",
                            Name = "Tablets",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "...",
                            Name = "Wearables",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "...",
                            Name = "Audio",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "...",
                            Name = "Video",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "...",
                            Name = "Gaming",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "...",
                            Name = "Office",
                            ParentCategoryId = 1
                        });
                });

            modelBuilder.Entity("SmartStock.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            IsActive = true,
                            Name = "Product 1",
                            Price = 999.99m,
                            SKU = "SKU-001"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            IsActive = true,
                            Name = "Product 2",
                            Price = 899.99m,
                            SKU = "SKU-002"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            IsActive = true,
                            Name = "Product 3",
                            Price = 799.99m,
                            SKU = "SKU-003"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            IsActive = true,
                            Name = "Product 4",
                            Price = 699.99m,
                            SKU = "SKU-004"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            IsActive = true,
                            Name = "Product 5",
                            Price = 599.99m,
                            SKU = "SKU-005"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            IsActive = true,
                            Name = "Product 6",
                            Price = 499.99m,
                            SKU = "SKU-006"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            IsActive = true,
                            Name = "Product 7",
                            Price = 399.99m,
                            SKU = "SKU-007"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            IsActive = true,
                            Name = "Product 8",
                            Price = 299.99m,
                            SKU = "SKU-008"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            IsActive = true,
                            Name = "Product 9",
                            Price = 199.99m,
                            SKU = "SKU-009"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            IsActive = true,
                            Name = "Product 10",
                            Price = 99.99m,
                            SKU = "SKU-010"
                        });
                });

            modelBuilder.Entity("SmartStock.Shared.Category", b =>
                {
                    b.HasOne("SmartStock.Shared.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("SmartStock.Shared.Product", b =>
                {
                    b.HasOne("SmartStock.Shared.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartStock.Shared.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
